[package]
name = "rust-backend-course"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
diesel = { version = "2.2.6", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0"
json = "0.12"
